apiVersion: v1
data:
  env.prefix: QaTest
kind: ConfigMap
metadata:
  labels:
    app: helloworld
    env: qa
  name: qa-properties-f9m45d9khk
  namespace: qa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
    env: qa
    visualize: "true"
  name: hello-world-service
  namespace: qa
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
    env: qa
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
    env: qa
  name: hello-world
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
      env: qa
  template:
    metadata:
      labels:
        app: helloworld
        env: qa
        visualize: "true"
    spec:
      containers:
      - env:
        - name: DEMO_GREETING
          value: Hello from the environment
        - name: DEMO_FAREWELL
          value: Such a sweet sorrow
        - name: ENV_PREFIX
          valueFrom:
            configMapKeyRef:
              key: env.prefix
              name: qa-properties-f9m45d9khk
        image: tykola/hello-spring:qa
        imagePullPolicy: Always
        name: hello-world-pod
        ports:
        - containerPort: 8080
